name: Test python scripts

# Run every time a new commit is pushed
on: push

jobs:
  # Set the job key
  test-scripts:
    # Name the job
    name: run python scripts
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: SE-env
          environment-file: environment.yml
          python-version: 3.8.8    

      - name: Execute all scripts
        shell: bash -l {0}
        run: |
          conda activate SE-env 
          cd scripts
          for script in scripts/*; 
          do
           python3 $script;
           done
          
          

